/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by customer type
SELECT 
	customer_type,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY customer_type
ORDER BY total_customers DESC;

-- Find total products by category
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average cost in each category?
SELECT
	dp.category,
	AVG(fs.total_product_cost) as avg_product_cost
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY avg_product_cost DESC;

-- What is the total revenue generated for each category?
SELECT
	dp.category,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customer/store
SELECT
	dc.name,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
	ON fs.customer_key = dc.customer_key
GROUP BY dc.name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
	dt.name AS country_name,
	SUM(fs.order_quantity) as sold_items
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_territory AS dt
	ON fs.territory_key = dt.territory_key
GROUP BY dt.name
ORDER BY sold_items DESC;

-- Find total products by subcategory
SELECT
	dp.subcategory,
	COUNT(fs.product_key) as total_product
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
GROUP BY dp.subcategory
ORDER BY total_product DESC;

-- Find total products by color
SELECT
	color,
	COUNT(product_key) as total_product
FROM gold.dim_products
GROUP BY color
ORDER BY total_product DESC;

-- Find total products by size
SELECT
	size,
	COUNT(product_key) as total_product
FROM gold.dim_products
GROUP BY size
ORDER BY total_product DESC;

-- What is the average list price by category?
SELECT
	category,
	COUNT(list_price) as avg_list_price
FROM gold.dim_products
GROUP BY category
ORDER BY avg_list_price DESC;

-- What is the total revenue by territory group?
SELECT
	dt.group_name,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_territory AS dt
	ON fs.territory_key = dt.territory_key
GROUP BY dt.group_name
ORDER BY total_revenue DESC;

-- Find total revenue by salesperson 
SELECT
	dsp.sales_person_id,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_sales_persons AS dsp
	ON fs.sales_person_key = dsp.sales_person_key
WHERE dsp.sales_person_id IS NOT NULL
GROUP BY dsp.sales_person_id
ORDER BY total_revenue DESC;

-- Find total revenue by salesperson job title
SELECT
	dsp.job_title,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_sales_persons AS dsp
	ON fs.sales_person_key = dsp.sales_person_key
WHERE dsp.sales_person_id IS NOT NULL
GROUP BY dsp.job_title
ORDER BY total_revenue DESC;

-- Find total revenue by year
SELECT
	dd.year,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_dates AS dd
	ON fs.date_key = dd.date_key
GROUP BY dd.year
ORDER BY dd.year;

-- Find total revenue by year and month
SELECT
	dd.month_name,
	dd.year,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_dates AS dd
	ON fs.date_key = dd.date_key
GROUP BY dd.month_name, dd.year
ORDER BY total_revenue DESC;

-- Find total revenue by quarter
SELECT
	dd.quarter,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_dates AS dd
	ON fs.date_key = dd.date_key
GROUP BY dd.quarter
ORDER BY dd.quarter;

-- Find total orders by day of week
SELECT
	dd.day_of_week,
	COUNT(DISTINCT fs.sales_order_detail_id) as total_orders
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_dates AS dd
	ON fs.date_key = dd.date_key
GROUP BY dd.day_of_week
ORDER BY dd.day_of_week;

-- Find total quantity sold by category
SELECT
	dp.category,
	SUM(fs.order_quantity) as total_quantity
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_quantity DESC;


-- Find total gross profit by category
SELECT
	dp.category,
	SUM(fs.gross_profit) as total_gross_profit
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_gross_profit DESC;
