-- Find total customers by customer type
SELECT 
	customer_type,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY customer_type
ORDER BY total_customers DESC;

-- Find total products by category
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average cost in each category?
SELECT
	dp.category,
	AVG(fs.total_product_cost) as avg_product_cost
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY avg_product_cost DESC;

-- What is the total revenue generated for each category?
SELECT
	dp.category,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customer
SELECT
	dc.name,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
	ON fs.customer_key = dc.customer_key
WHERE dc.customer_type = 'Individual'
GROUP BY dc.name
ORDER BY total_revenue DESC;
-- What is the distribution of sold items across countries?

-- Find total products by subcategory
-- Find total products by color
-- Find total products by size
-- What is the average list price by category?
-- What is the total revenue by territory group?
-- Find total revenue by salesperson
-- Find total revenue by salesperson job title
-- Find total revenue by year
-- Find total revenue by year and month
-- Find total revenue by quarter
-- Find total orders by day of week
-- Find total quantity sold by category
-- Find total gross profit by category
